env:
  name: boilerplate-business
  description: Service for business implementations.

logging:
  disable_existing_loggers: True
  version: 1
  formatters:
    formatter:
      format: "[%(asctime)s] [%(levelname)s] [${ENV}] [${SERVICE_NAME}] [%(name)s]: %(message)s"
  handlers:
    console:
      class: "logging.StreamHandler"
      level: "INFO"
      formatter: "formatter"
  root:
    level: "INFO"
    handlers: ["console"]
